name: motionhack_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/illustration1.png
    - assets/images/illustration2.png
    - assets/images/illustration3.png
    - assets/images/illustration4.png
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/images/clock.png
    - assets/images/image.png
    - assets/images/notification.png
    - assets/images/person.png
    - assets/images/profil.png
    - assets/images/robot.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\poppins\Poppins-Light.ttf
          weight: 300
        - asset: assets\fonts\poppins\Poppins-Regular.ttf
          weight: 400
        - asset: assets\fonts\poppins\Poppins-Medium.ttf
          weight: 500
        - asset: assets\fonts\poppins\Poppins-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\poppins\Poppins-Bold.ttf
          weight: 700
